package envgen

import (
	"fmt"
	"os"
	"strings"
)

// GenerateSync writes the environment variables to .env.hostbind
// and ensures .env.hostbind is present in .gitignore
func GenerateSync(dir string, envVars map[string]string) error {
	envFile := fmt.Sprintf("%s/.env.hostbind", dir)

	// Build env file content
	var content strings.Builder
	content.WriteString("# Generated by HostBind. DO NOT EDIT.\n")
	content.WriteString("# These values change per machine and per worktree.\n\n")

	for k, v := range envVars {
		content.WriteString(fmt.Sprintf("%s=%s\n", k, v))
	}

	if err := os.WriteFile(envFile, []byte(content.String()), 0644); err != nil {
		return fmt.Errorf("failed to write .env.hostbind: %w", err)
	}

	// Update .gitignore
	gitignoreFile := fmt.Sprintf("%s/.gitignore", dir)
	
	// Create .gitignore if it doesn't exist
	if _, err := os.Stat(gitignoreFile); os.IsNotExist(err) {
		return os.WriteFile(gitignoreFile, []byte(".env.hostbind\n"), 0644)
	}

	// Read existing .gitignore
	b, err := os.ReadFile(gitignoreFile)
	if err != nil {
		return fmt.Errorf("failed to read .gitignore: %w", err)
	}
	
	ignoreContent := string(b)
	if !strings.Contains(ignoreContent, ".env.hostbind") {
		// Ensure newline before appending if needed
		if len(ignoreContent) > 0 && !strings.HasSuffix(ignoreContent, "\n") {
			ignoreContent += "\n"
		}
		ignoreContent += ".env.hostbind\n"
		return os.WriteFile(gitignoreFile, []byte(ignoreContent), 0644)
	}

	return nil
}
